name: Node.js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

  validate-commit-message:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check commit message format
      run: |
        # Check if the latest commit message matches the Jira ID pattern
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        JIRA_PATTERN='^[A-Z]+-\d+'
        if ! echo "$COMMIT_MESSAGE" | grep -qE "$JIRA_PATTERN"; then
          echo "Error: Commit message does not include a Jira ID."
          echo "Expected format: PROJ-123"
          exit 1
        fi
        echo "Commit message is valid."

  deploy:
    runs-on: ubuntu-latest
    needs: [build, validate-commit-message]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy
      run: |
        echo "Deploying to production server..."
        # Add your deployment script here
